"""Augment a processed graph with synthetic fraud nodes generated by a trained TabDDPM model
(see training/train_diffusion.py). Synthetic nodes are added to the TRAIN split only — val/test
stay exactly as they were, so evaluation always measures generalization to real data."""

import argparse
import logging
from collections import defaultdict
from pathlib import Path

import torch
import yaml
from torch_geometric.data import Data

from models.diffusion.tabddpm import GaussianDiffusion, TabDDPMDenoiser

ROOT = Path(__file__).resolve().parent.parent
logger = logging.getLogger(__name__)


def load_config(path: str) -> dict:
    with open(path) as f:
        return yaml.safe_load(f)


def pick_device() -> torch.device:
    if torch.cuda.is_available():
        return torch.device("cuda")
    if torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def run_from_config(config: dict) -> Path:
    logger.info(f"augment_graph config: {config}")
    acfg = config["augment"]
    device = pick_device()

    data = torch.load(ROOT / config["data"]["processed_path"], weights_only=False)

    ckpt = torch.load(ROOT / config["diffusion"]["model_path"], map_location=device, weights_only=False)
    denoiser = TabDDPMDenoiser(feature_dim=ckpt["feature_dim"], hidden_dim=ckpt["hidden_dim"]).to(device)
    denoiser.load_state_dict(ckpt["denoiser_state"])
    denoiser.eval()
    diffusion = GaussianDiffusion(num_timesteps=ckpt["num_timesteps"], device=device)

    n_synthetic = acfg["n_synthetic"]
    sampler = acfg.get("sampler", "ddim")

    # Per-feature clamp of the predicted x0 at every reverse step, bounded to real fraud train
    # features' own mean +/- 3*std. Without this, reverse-process errors compound over many steps
    # and the sampled features explode in scale (observed on Elliptic: fully-trained 1000-epoch
    # model produced std~78-110 vs real fraud's std~0.56, a ~150x blowup — see LAB_JOURNAL.md
    # Run 33/34). Real fraud-only TRAIN features are the reference distribution, matching what the
    # denoiser was actually trained on.
    clamp_x0 = None
    if acfg.get("clamp_synthetic", True):
        real_fraud_x = data.x[data.train_mask & (data.y == 1)]
        mu, sd = real_fraud_x.mean(dim=0), real_fraud_x.std(dim=0).clamp(min=1e-3)
        n_clamp_std = acfg.get("clamp_std", 3.0)
        clamp_x0 = ((mu - n_clamp_std * sd).to(device), (mu + n_clamp_std * sd).to(device))

    if sampler == "ddim":
        synthetic_x = diffusion.ddim_sample(
            denoiser, n_synthetic, ckpt["feature_dim"], device,
            ddim_steps=acfg.get("ddim_steps", 50), clamp_x0=clamp_x0,
        )
    elif sampler == "ddpm":
        synthetic_x = diffusion.ddpm_sample(denoiser, n_synthetic, ckpt["feature_dim"], device, clamp_x0=clamp_x0)
    else:
        raise ValueError(f"Unknown augment.sampler: {sampler!r} (expected 'ddim' or 'ddpm')")
    synthetic_x = synthetic_x.cpu()
    logger.info(f"Generated {n_synthetic} synthetic fraud feature vectors via {sampler} sampling "
                f"(mean={synthetic_x.mean().item():.3f}, std={synthetic_x.std().item():.3f}, "
                f"clamp_x0={'on, ' + str(n_clamp_std) + 'std' if clamp_x0 is not None else 'off'})")

    n_original = data.num_nodes
    new_indices = torch.arange(n_original, n_original + n_synthetic)
    train_idx = data.train_mask.nonzero(as_tuple=True)[0]

    # attach_to="fraud_only" restricts candidate connections to real fraud TRAIN nodes instead of
    # the whole TRAIN pool. attach_to="template" is a different mechanism entirely — see below.
    # Default ("all") preserves original behavior. On PaySim's huge graph (~1.9M train nodes)
    # attaching to the whole pool only perturbs ~1% of train nodes regardless; on Elliptic's much
    # smaller graph (~30K train nodes) the same k_connections/n_synthetic recipe attached ~44% of
    # ALL train nodes (mostly legit) to a synthetic fraud neighbor — a much bigger, uncontrolled
    # structural perturbation, and a plausible cause of Run 33's uniformly bad sweep.
    attach_to = acfg.get("attach_to", "all")
    generator = torch.Generator().manual_seed(config["seed"])
    src, dst = [], []

    if attach_to == "template":
        # Structure-preserving augmentation (2026-07-21 discussion): attaching each synthetic node
        # to k RANDOM nodes invents edges that don't reflect how real fraud nodes actually connect
        # — arguably vandalizing the graph's structural invariants rather than augmenting them,
        # which could explain why diffusion augmentation gives only modest/inconsistent GNN gains
        # despite a plain Random Forest on raw features beating every GNN variant (Run 40): RF
        # never relies on structure, so it's unaffected by this; the GNN is. Here, each synthetic
        # node clones a REAL fraud TRAIN node's actual local neighborhood (not a fixed k) — same
        # real edges a real fraud node has, fresh independently-diffused features. This is
        # deliberately NOT full graph structure generation (that's a much harder open problem, see
        # CLAUDE.md's "Approach 3: Graph Structure Diffusion") — just reusing real local topology
        # as a template instead of inventing new, structurally-arbitrary edges.
        adj = defaultdict(list)
        for s, d in zip(data.train_edge_index[0].tolist(), data.train_edge_index[1].tolist()):
            adj[s].append(d)
        fraud_train_idx = train_idx[data.y[train_idx] == 1]
        template_pool = torch.tensor([t for t in fraud_train_idx.tolist() if len(adj[t]) > 0])
        if template_pool.numel() == 0:
            raise ValueError("attach_to='template': no real fraud TRAIN node has any neighbor "
                              "in train_edge_index to use as a template.")
        for new_idx in new_indices.tolist():
            template = template_pool[torch.randint(0, template_pool.numel(), (1,), generator=generator)].item()
            for c in adj[template]:
                src.extend([new_idx, c])
                dst.extend([c, new_idx])
    elif attach_to in ("fraud_only", "all"):
        if attach_to == "fraud_only":
            train_idx = train_idx[data.y[train_idx] == 1]
        # Attach each synthetic fraud node to a random sample of real TRAIN nodes, so it actually
        # participates in message passing (like a real transaction touching real accounts) instead
        # of sitting isolated in the graph.
        k_connections = acfg.get("k_connections", 5)
        for new_idx in new_indices.tolist():
            chosen = train_idx[torch.randint(0, train_idx.numel(), (k_connections,), generator=generator)]
            for c in chosen.tolist():
                src.extend([new_idx, c])
                dst.extend([c, new_idx])
    else:
        raise ValueError(f"Unknown augment.attach_to: {attach_to!r} (expected 'all', 'fraud_only', or 'template')")

    new_edge_index = torch.tensor([src, dst], dtype=torch.long)
    # Synthetic nodes are TRAIN-only (see augmented_train_mask below) — their edges belong in
    # train_edge_index specifically, not the full/val edge views. val_edge_index and the full
    # edge_index carry over UNCHANGED: val/test nodes' real neighborhoods never include synthetic
    # nodes, so nothing there needs updating, and this keeps the leakage-free temporal edge split
    # (data/temporal_edges.py) intact through augmentation instead of silently re-introducing it.
    augmented_train_edge_index = torch.cat([data.train_edge_index, new_edge_index], dim=1)

    augmented_x = torch.cat([data.x, synthetic_x], dim=0)
    augmented_y = torch.cat([data.y, torch.ones(n_synthetic, dtype=data.y.dtype)])
    augmented_train_mask = torch.cat([data.train_mask, torch.ones(n_synthetic, dtype=torch.bool)])
    augmented_val_mask = torch.cat([data.val_mask, torch.zeros(n_synthetic, dtype=torch.bool)])
    augmented_test_mask = torch.cat([data.test_mask, torch.zeros(n_synthetic, dtype=torch.bool)])

    augmented_data = Data(
        x=augmented_x,
        edge_index=data.edge_index,
        train_edge_index=augmented_train_edge_index,
        val_edge_index=data.val_edge_index,
        y=augmented_y,
        train_mask=augmented_train_mask,
        val_mask=augmented_val_mask,
        test_mask=augmented_test_mask,
    )

    out_path = ROOT / config["data"]["augmented_processed_path"]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    torch.save(augmented_data, out_path)
    logger.info(f"Saved augmented graph ({n_original} -> {augmented_data.num_nodes} nodes, "
                f"+{n_synthetic} synthetic fraud, train_edge_index={augmented_train_edge_index.shape[1]} "
                f"directed edges) to {out_path}")
    return out_path


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", required=True)
    args = parser.parse_args()
    config = load_config(args.config)
    run_from_config(config)


if __name__ == "__main__":
    main()
