"""Augment a processed graph with synthetic fraud nodes generated by a trained TabDDPM model
(see training/train_diffusion.py). Synthetic nodes are added to the TRAIN split only — val/test
stay exactly as they were, so evaluation always measures generalization to real data."""

import argparse
from pathlib import Path

import torch
import yaml
from torch_geometric.data import Data

from models.diffusion.tabddpm import GaussianDiffusion, TabDDPMDenoiser

ROOT = Path(__file__).resolve().parent.parent


def load_config(path: str) -> dict:
    with open(path) as f:
        return yaml.safe_load(f)


def pick_device() -> torch.device:
    if torch.cuda.is_available():
        return torch.device("cuda")
    if torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def run_from_config(config: dict) -> Path:
    print(f"augment_graph config: {config}")
    acfg = config["augment"]
    device = pick_device()

    data = torch.load(ROOT / config["data"]["processed_path"], weights_only=False)

    ckpt = torch.load(ROOT / config["diffusion"]["model_path"], map_location=device, weights_only=False)
    denoiser = TabDDPMDenoiser(feature_dim=ckpt["feature_dim"], hidden_dim=ckpt["hidden_dim"]).to(device)
    denoiser.load_state_dict(ckpt["denoiser_state"])
    denoiser.eval()
    diffusion = GaussianDiffusion(num_timesteps=ckpt["num_timesteps"], device=device)

    n_synthetic = acfg["n_synthetic"]
    sampler = acfg.get("sampler", "ddim")
    if sampler == "ddim":
        synthetic_x = diffusion.ddim_sample(
            denoiser, n_synthetic, ckpt["feature_dim"], device, ddim_steps=acfg.get("ddim_steps", 50),
        )
    elif sampler == "ddpm":
        synthetic_x = diffusion.ddpm_sample(denoiser, n_synthetic, ckpt["feature_dim"], device)
    else:
        raise ValueError(f"Unknown augment.sampler: {sampler!r} (expected 'ddim' or 'ddpm')")
    synthetic_x = synthetic_x.cpu()
    print(f"Generated {n_synthetic} synthetic fraud feature vectors via {sampler} sampling "
          f"(mean={synthetic_x.mean().item():.3f}, std={synthetic_x.std().item():.3f})")

    n_original = data.num_nodes
    new_indices = torch.arange(n_original, n_original + n_synthetic)
    train_idx = data.train_mask.nonzero(as_tuple=True)[0]

    # attach_to="fraud_only" restricts candidate connections to real fraud TRAIN nodes instead of
    # the whole TRAIN pool. Default ("all") preserves original behavior. On PaySim's huge graph
    # (~1.9M train nodes) attaching to the whole pool only perturbs ~1% of train nodes regardless;
    # on Elliptic's much smaller graph (~30K train nodes) the same k_connections/n_synthetic recipe
    # attached ~44% of ALL train nodes (mostly legit) to a synthetic fraud neighbor — a much bigger,
    # uncontrolled structural perturbation, and a plausible cause of Run 33's uniformly bad sweep.
    attach_to = acfg.get("attach_to", "all")
    if attach_to == "fraud_only":
        train_idx = train_idx[data.y[train_idx] == 1]
    elif attach_to != "all":
        raise ValueError(f"Unknown augment.attach_to: {attach_to!r} (expected 'all' or 'fraud_only')")

    # Attach each synthetic fraud node to a random sample of real TRAIN nodes, so it actually
    # participates in message passing (like a real transaction touching real accounts) instead
    # of sitting isolated in the graph.
    k_connections = acfg.get("k_connections", 5)
    generator = torch.Generator().manual_seed(config["seed"])
    src, dst = [], []
    for new_idx in new_indices.tolist():
        chosen = train_idx[torch.randint(0, train_idx.numel(), (k_connections,), generator=generator)]
        for c in chosen.tolist():
            src.extend([new_idx, c])
            dst.extend([c, new_idx])
    new_edge_index = torch.tensor([src, dst], dtype=torch.long)
    augmented_edge_index = torch.cat([data.edge_index, new_edge_index], dim=1)

    augmented_x = torch.cat([data.x, synthetic_x], dim=0)
    augmented_y = torch.cat([data.y, torch.ones(n_synthetic, dtype=data.y.dtype)])
    augmented_train_mask = torch.cat([data.train_mask, torch.ones(n_synthetic, dtype=torch.bool)])
    augmented_val_mask = torch.cat([data.val_mask, torch.zeros(n_synthetic, dtype=torch.bool)])
    augmented_test_mask = torch.cat([data.test_mask, torch.zeros(n_synthetic, dtype=torch.bool)])

    augmented_data = Data(
        x=augmented_x,
        edge_index=augmented_edge_index,
        y=augmented_y,
        train_mask=augmented_train_mask,
        val_mask=augmented_val_mask,
        test_mask=augmented_test_mask,
    )

    out_path = ROOT / config["data"]["augmented_processed_path"]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    torch.save(augmented_data, out_path)
    print(f"Saved augmented graph ({n_original} -> {augmented_data.num_nodes} nodes, "
          f"+{n_synthetic} synthetic fraud, {augmented_edge_index.shape[1]} directed edges) "
          f"to {out_path}")
    return out_path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", required=True)
    args = parser.parse_args()
    config = load_config(args.config)
    run_from_config(config)


if __name__ == "__main__":
    main()
